export const BACKFILL_CHUNK_DAYS_DEFAULT = 7;
export const BACKFILL_EARLIEST = "1990-01-01";
export const PAGE_SIZE_LIMIT = 10_000;
export const BACKFILL_QUEUE_CONCURRENCY = 6;
export const BACKFILL_HCC_CONCURRENCY = 8;
export const MAX_BACKFILL_ENQUEUE_PER_WAVE = 3000;
